# Generated by Django 2.0.12 on 2019-08-17 11:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CronConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron_second', models.CharField(default='*', max_length=10, verbose_name='分')),
                ('cron_minute', models.CharField(default='*', max_length=10, verbose_name='分')),
                ('cron_hour', models.CharField(default='*', max_length=10, verbose_name='时')),
                ('cron_day', models.CharField(default='*', max_length=10, verbose_name='天')),
                ('cron_month', models.CharField(default='*', max_length=10, verbose_name='月')),
                ('cron_week', models.CharField(default='*', max_length=10, verbose_name='周')),
                ('cron_name', models.CharField(default='every 1 second', max_length=100, unique=True, verbose_name='Cron名称')),
            ],
            options={
                'verbose_name': 'Cron配置',
                'db_table': 'opsmanage_cron_config',
            },
        ),
        migrations.CreateModel(
            name='CronLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False, verbose_name='log_id')),
                ('job_id', models.CharField(max_length=255, verbose_name='job_id')),
                ('status', models.CharField(max_length=10, verbose_name='task_cmd')),
                ('task_cmd', models.CharField(max_length=150, verbose_name='task_cmd')),
                ('task_log', models.TextField(verbose_name='task_log')),
                ('exec_time', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
            ],
            options={
                'verbose_name': 'Cron执行日志',
                'db_table': 'cron_log',
                'ordering': ('-exec_time',),
            },
        ),
        migrations.CreateModel(
            name='MailAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_list', models.TextField(default='actanble@gmail.com,actanble@163.com,admin@actanble.com', verbose_name='收件的邮件列表')),
                ('header', models.CharField(default='CSO管理平台', max_length=50, verbose_name='发送邮件显示名称')),
                ('sub', models.CharField(default='告警', max_length=200, verbose_name='发送邮件的标题')),
                ('content', models.TextField(default='空', verbose_name='邮件内容')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '邮件发送审计',
                'db_table': 'mail_audits',
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='MailHost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_host', models.CharField(default='smtp.163.com', help_text='邮件服务端地址例如smtp.163.com', max_length=255, verbose_name='邮件服务端地址')),
                ('mail_user', models.CharField(help_text='邮件用户名root', max_length=255, verbose_name='邮件用户名')),
                ('mail_pass', models.CharField(help_text='邮件设置的棉麻', max_length=255, verbose_name='邮件用户名')),
                ('mail_postfix', models.CharField(default='163.com', help_text='邮件用户名root', max_length=255, verbose_name='邮件后缀')),
                ('default_recv', models.CharField(default='180573956@qq.com,admin@actanble.com', max_length=255, verbose_name='默认接收者')),
                ('active', models.BooleanField(default=True, verbose_name='生效')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='审计时间')),
            ],
            options={
                'verbose_name': '邮件服务端列表',
                'db_table': 'mail_hosts',
                'ordering': ('active', '-date_created'),
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False, verbose_name='log_id')),
                ('log_key', models.CharField(max_length=150, verbose_name='log_key')),
                ('task_level', models.IntegerField()),
                ('log_info', models.TextField()),
                ('exec_time', models.BigIntegerField()),
                ('log_time', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
            ],
            options={
                'verbose_name': 'scheduler_task 执行日志',
                'db_table': 'scheduler_task_log',
                'ordering': ('-log_time', '-task_level'),
            },
        ),
        migrations.AddField(
            model_name='mailaudit',
            name='mail_host',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail_host_audits', to='ops.MailHost', verbose_name='Mail Host'),
        ),
    ]
