# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-28 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='/waf/mg/jwt_login/', max_length=255, verbose_name='请求URL')),
                ('request_method', models.CharField(default='POST', max_length=255, verbose_name='请求方法')),
                ('ip', models.GenericIPAddressField(default='0.0.0.0', verbose_name='IP')),
                ('username', models.CharField(max_length=255, verbose_name='访问的用户的用户名')),
                ('status', models.CharField(choices=[('200', '正常'), ('400', '请求错误'), ('403', '访问阻断'), ('401', '认证失败')], default='200', max_length=5, verbose_name='请求状态')),
                ('opreate_time', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
                ('param', models.CharField(default='', max_length=255, verbose_name='参数')),
            ],
            options={
                'verbose_name': '审计用户操作',
                'db_table': 'user_auditlog',
            },
        ),
    ]
