# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-28 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_userauditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userauditlog',
            options={'ordering': ['-opreate_time'], 'verbose_name': '审计用户操作'},
        ),
    ]
