# Generated by Django 2.1.7 on 2019-06-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scantask',
            name='atnow',
            field=models.BooleanField(blank=True, default=True, verbose_name='立即执行'),
        ),
        migrations.AlterField(
            model_name='scantask',
            name='regular',
            field=models.DateTimeField(default='2011-11-11 11:11:11', verbose_name='定时执行'),
        ),
    ]
