# Generated by Django 2.1.7 on 2019-05-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scantool',
            name='_kwargs',
        ),
        migrations.AddField(
            model_name='scantool',
            name='args',
            field=models.CharField(default='', help_text='扫描参数-h', max_length=100, verbose_name='需要准备的参数集合'),
        ),
    ]
