# Generated by Django 2.1.7 on 2019-06-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanscript',
            options={'verbose_name': '扫描脚本集合'},
        ),
        migrations.AddField(
            model_name='scanrecode',
            name='exported',
            field=models.BooleanField(default=False, verbose_name='是否被导出'),
        ),
    ]
