# Generated by Django 2.1.7 on 2019-06-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0002_auto_20190605_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='scantask',
            name='udp',
            field=models.BooleanField(default=False, verbose_name='增加UDP扫描'),
        ),
    ]
