# Generated by Django 2.1.7 on 2019-06-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0002_scanscript_args'),
    ]

    operations = [
        migrations.AddField(
            model_name='scantool',
            name='install',
            field=models.TextField(default='', verbose_name='执行的脚本命令行'),
        ),
        migrations.AddField(
            model_name='scantool',
            name='judge_script',
            field=models.TextField(default='', verbose_name='判断是否在程序中的脚本'),
        ),
        migrations.AddField(
            model_name='scantool',
            name='summary',
            field=models.TextField(default='', verbose_name='工具概要'),
        ),
    ]
