# Generated by Django 2.1.7 on 2019-06-05 11:21

from django.db import migrations, models
import scan.models.task


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0003_scantask_udp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scantask',
            name='regular',
            field=models.DateTimeField(default=scan.models.task.YESTERDAT, verbose_name='定时执行'),
        ),
    ]
