# Generated by Django 2.1.7 on 2019-06-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0004_auto_20190605_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scantask',
            name='crontab',
            field=models.CharField(blank=True, default='0 0 * * *', max_length=55, verbose_name='Crontab模式'),
        ),
        migrations.AlterField(
            model_name='scantask',
            name='interval',
            field=models.IntegerField(blank=True, default=86400, help_text='3600* 2', verbose_name='定时扫描'),
        ),
    ]
