# Generated by Django 2.1.7 on 2019-05-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0005_auto_20190524_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nmapservicename',
            name='service_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='服务名'),
        ),
    ]
