# Generated by Django 2.1.7 on 2019-05-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0006_auto_20190524_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrecode',
            name='script',
            field=models.TextField(blank=True, verbose_name='完整的执行脚本'),
        ),
    ]
