port_data = {
    'data': [{'port': '1 ', 'portname': 'tcpmux ', 'desc': 'TCP 端口服务多路复用 ', 'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '5 ', 'portname': 'rje ', 'desc': '远程作业入口 ', 'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '7 ', 'portname': 'echo ', 'desc': 'Echo 服务 ', 'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '9 ', 'portname': 'discard ', 'desc': '用于连接测试的空服务 ', 'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '11 ', 'portname': 'systat ', 'desc': '用于列举连接了的端口的系统状态 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '13 ', 'portname': 'daytime ', 'desc': '给请求主机发送日期和时间 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '17 ', 'portname': 'qotd ', 'desc': '给连接了的主机发送每日格言 ', 'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '18 ', 'portname': 'msp ', 'desc': '消息发送协议 ', 'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '19 ', 'portname': 'chargen ', 'desc': '字符生成服务；发送无止境的字符流 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '20 ', 'portname': 'ftp-data ', 'desc': 'FTP 数据端口 ', 'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '21 ', 'portname': 'ftp ', 'desc': '文件传输协议（FTP）端口；有时被文件服务协议（FSP）使用 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '22 ', 'portname': 'ssh ', 'desc': '安全 Shell（SSH）服务 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '23 ', 'portname': 'telnet ', 'desc': 'Telnet 服务 ', 'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '25 ', 'portname': 'smtp ', 'desc': '简单邮件传输协议（SMTP） ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '37 ', 'portname': 'time ', 'desc': '时间协议 ', 'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '39 ', 'portname': 'rlp ', 'desc': '资源定位协议 ', 'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '42 ', 'portname': 'nameserver ', 'desc': '互联网名称服务 ', 'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '43 ', 'portname': 'nicname ', 'desc': 'WHOIS 目录服务 ', 'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '49 ', 'portname': 'tacacs ', 'desc': '用于基于 TCP/IP 验证和访问的终端访问控制器访问控制系统 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '50 ', 'portname': 're-mail-ck ', 'desc': '远程邮件检查协议 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '53 ', 'portname': 'domain ', 'desc': '域名服务（如 BIND） ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '63 ', 'portname': 'whois++ ', 'desc': 'WHOIS++，被扩展了的 WHOIS 服务 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '67 ', 'portname': 'bootps ', 'desc': '引导协议（BOOTP）服务；还被动态主机配置协议（DHCP）服务使用 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '68 ', 'portname': 'bootpc ', 'desc': 'Bootstrap（BOOTP）客户；还被动态主机配置协议（DHCP）客户使用 ',
              'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '69 ', 'portname': 'tftp ', 'desc': '小文件传输协议（TFTP） ', 'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '70 ', 'portname': 'gopher ', 'desc': 'Gopher 互联网文档搜寻和检索 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '71 ', 'portname': 'netrjs-1 ', 'desc': '远程作业服务 ', 'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '72 ', 'portname': 'netrjs-2 ', 'desc': '远程作业服务 ', 'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '73 ', 'portname': 'netrjs-3 ', 'desc': '远程作业服务 ', 'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '73 ', 'portname': 'netrjs-4 ', 'desc': '远程作业服务 ', 'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '79 ', 'portname': 'finger ', 'desc': '用于用户联系信息的 Finger 服务 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '80 ', 'portname': 'http ', 'desc': '用于万维网（WWW）服务的超文本传输协议（HTTP） ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '88 ', 'portname': 'kerberos ', 'desc': 'Kerberos 网络验证系统 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '95 ', 'portname': 'supdup ', 'desc': 'Telnet 协议扩展 ', 'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '101 ', 'portname': 'hostname ', 'desc': 'SRI-NIC 机器上的主机名服务 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '102 ', 'portname': 'iso-tsap ', 'desc': 'ISO 开发环境（ISODE）网络应用 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '105 ', 'portname': 'csnet-ns ', 'desc': '邮箱名称服务器；也被 CSO 名称服务器使用 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '107 ', 'portname': 'rtelnet ', 'desc': '远程 Telnet ', 'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '109 ', 'portname': 'pop2 ', 'desc': '邮局协议版本2 ', 'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '110 ', 'portname': 'pop3 ', 'desc': '邮局协议版本3 ', 'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '111 ', 'portname': 'sunrpc ', 'desc': '用于远程命令执行的远程过程调用（RPC）协议，被网络文件系统（NFS）使用 ',
              'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '113 ', 'portname': 'auth ', 'desc': '验证和身份识别协议 ', 'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '115 ', 'portname': 'sftp ', 'desc': '安全文件传输协议（SFTP）服务 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '117 ', 'portname': 'uucp-path ', 'desc': 'Unix 到 Unix 复制协议（UUCP）路径服务 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '119 ', 'portname': 'nntp ', 'desc': '用于 USENET 讨论系统的网络新闻传输协议（NNTP） ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '123 ', 'portname': 'ntp ', 'desc': '网络时间协议（NTP） ', 'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '137 ', 'portname': 'netbios-ns ', 'desc': '在红帽企业 Linux 中被 Samba 使用的 NETBIOS 名称服务 ',
              'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '138 ', 'portname': 'netbios-dgm ', 'desc': '在红帽企业 Linux 中被 Samba 使用的 NETBIOS 数据报服务 ',
              'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '139 ', 'portname': 'netbios-ssn ', 'desc': '在红帽企业 Linux 中被 Samba 使用的NET BIOS 会话服务 ',
              'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '143 ', 'portname': 'imap ', 'desc': '互联网消息存取协议（IMAP） ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '161 ', 'portname': 'snmp ', 'desc': '简单网络管理协议（SNMP） ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '162 ', 'portname': 'snmptrap ', 'desc': 'SNMP 的陷阱 ', 'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '163 ', 'portname': 'cmip-man ', 'desc': '通用管理信息协议（CMIP） ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '164 ', 'portname': 'cmip-agent ', 'desc': '通用管理信息协议（CMIP） ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '174 ', 'portname': 'mailq ', 'desc': 'MAILQ ', 'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '177 ', 'portname': 'xdmcp ', 'desc': 'X 显示管理器控制协议 ', 'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '178 ', 'portname': 'nextstep ', 'desc': 'NeXTStep 窗口服务器 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '179 ', 'portname': 'bgp ', 'desc': '边界网络协议 ', 'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '191 ', 'portname': 'prospero ', 'desc': 'Cliffod Neuman 的 Prospero 服务 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '194 ', 'portname': 'irc ', 'desc': '互联网中继聊天（IRC） ', 'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '199 ', 'portname': 'smux ', 'desc': 'SNMP UNIX 多路复用 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '201 ', 'portname': 'at-rtmp ', 'desc': 'AppleTalk 选路 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '202 ', 'portname': 'at-nbp ', 'desc': 'AppleTalk 名称绑定 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '204 ', 'portname': 'at-echo ', 'desc': 'AppleTalk echo 服务 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '206 ', 'portname': 'at-zis ', 'desc': 'AppleTalk 区块信息 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '209 ', 'portname': 'qmtp ', 'desc': '快速邮件传输协议（QMTP） ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '210 ', 'portname': 'z39.50 ', 'desc': 'NISO Z39.50 数据库 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '213 ', 'portname': 'ipx ', 'desc': '互联网络分组交换协议（IPX），被 Novell Netware 环境常用的数据报协议 ',
              'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '220 ', 'portname': 'imap3 ', 'desc': '互联网消息存取协议版本3 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '245 ', 'portname': 'link ', 'desc': 'LINK ', 'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '347 ', 'portname': 'fatserv ', 'desc': 'Fatmen 服务器 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '363 ', 'portname': 'rsvp_tunnel ', 'desc': 'RSVP 隧道 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '369 ', 'portname': 'rpc2portmap ', 'desc': 'Coda 文件系统端口映射器 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '370 ', 'portname': 'codaauth2 ', 'desc': 'Coda 文件系统验证服务 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '372 ', 'portname': 'ulistproc ', 'desc': 'UNIX Listserv ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '389 ', 'portname': 'ldap ', 'desc': '轻型目录存取协议（LDAP） ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '427 ', 'portname': 'svrloc ', 'desc': '服务位置协议（SLP） ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '434 ', 'portname': 'mobileip-agent ', 'desc': '可移互联网协议（IP）代理 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '435 ', 'portname': 'mobilip-mn ', 'desc': '可移互联网协议（IP）管理器 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '443 ', 'portname': 'https ', 'desc': '安全超文本传输协议（HTTP） ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '444 ', 'portname': 'snpp ', 'desc': '小型网络分页协议 ', 'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '445 ', 'portname': 'microsoft-ds ', 'desc': '通过 TCP/IP 的服务器消息块（SMB） ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '464 ', 'portname': 'kpasswd ', 'desc': 'Kerberos 口令和钥匙改换服务 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '468 ', 'portname': 'photuris ', 'desc': 'Photuris 会话钥匙管理协议 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '487 ', 'portname': 'saft ', 'desc': '简单不对称文件传输（SAFT）协议 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '488 ', 'portname': 'gss-http ', 'desc': '用于 HTTP 的通用安全服务（GSS） ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '496 ', 'portname': 'pim-rp-disc ', 'desc': '用于协议独立的多址传播（PIM）服务的会合点发现（RP-DISC） ',
              'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '500 ', 'portname': 'isakmp ', 'desc': '互联网安全关联和钥匙管理协议（ISAKMP） ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '535 ', 'portname': 'iiop ', 'desc': '互联网内部对象请求代理协议（IIOP） ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '538 ', 'portname': 'gdomap ', 'desc': 'GNUstep 分布式对象映射器（GDOMAP） ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '546 ', 'portname': 'dhcpv6-client ', 'desc': '动态主机配置协议（DHCP）版本6客户 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '547 ', 'portname': 'dhcpv6-server ', 'desc': '动态主机配置协议（DHCP）版本6服务 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '554 ', 'portname': 'rtsp ', 'desc': '实时流播协议（RTSP） ', 'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '563 ', 'portname': 'nntps ', 'desc': '通过安全套接字层的网络新闻传输协议（NNTPS） ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '565 ', 'portname': 'whoami ', 'desc': 'whoami ', 'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '587 ', 'portname': 'submission ', 'desc': '邮件消息提交代理（MSA） ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '610 ', 'portname': 'npmp-local ', 'desc': '网络外设管理协议（NPMP）本地 / 分布式排队系统（DQS） ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '611 ', 'portname': 'npmp-gui ', 'desc': '网络外设管理协议（NPMP）GUI / 分布式排队系统（DQS） ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '612 ', 'portname': 'hmmp-ind ', 'desc': 'HMMP 指示 / DQS ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '631 ', 'portname': 'ipp ', 'desc': '互联网打印协议（IPP） ', 'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '636 ', 'portname': 'ldaps ', 'desc': '通过安全套接字层的轻型目录访问协议（LDAPS） ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '674 ', 'portname': 'acap ', 'desc': '应用程序配置存取协议（ACAP） ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '694 ', 'portname': 'ha-cluster ', 'desc': '用于带有高可用性的群集的心跳服务 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '749 ', 'portname': 'kerberos-adm ', 'desc': 'Kerberos 版本5（v5）的“kadmin”数据库管理 ',
              'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '750 ', 'portname': 'kerberos-iv ', 'desc': 'Kerberos 版本4（v4）服务 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '765 ', 'portname': 'webster ', 'desc': '网络词典 ', 'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '767 ', 'portname': 'phonebook ', 'desc': '网络电话簿 ', 'type': '著名端口', 'type_desc': '常用的普通端口'},
             {'port': '873 ', 'portname': 'rsync ', 'desc': 'rsync 文件传输服务 ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '992 ', 'portname': 'telnets ', 'desc': '通过安全套接字层的 Telnet（TelnetS） ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '993 ', 'portname': 'imaps ', 'desc': '通过安全套接字层的互联网消息存取协议（IMAPS） ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '994 ', 'portname': 'ircs ', 'desc': '通过安全套接字层的互联网中继聊天（IRCS） ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '995 ', 'portname': 'pop3s ', 'desc': '通过安全套接字层的邮局协议版本3（POPS3） ', 'type': '著名端口',
              'type_desc': '常用的普通端口'},
             {'port': '1 ', 'portname': 'tcpmux ', 'desc': 'TCP 端口服务多路复用 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '5 ', 'portname': 'rje ', 'desc': '远程作业入口 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '7 ', 'portname': 'echo ', 'desc': 'Echo 服务 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '9 ', 'portname': 'discard ', 'desc': '用于连接测试的空服务 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '11 ', 'portname': 'systat ', 'desc': '用于列举连接了的端口的系统状态 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '13 ', 'portname': 'daytime ', 'desc': '给请求主机发送日期和时间 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '17 ', 'portname': 'qotd ', 'desc': '给连接了的主机发送每日格言 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '18 ', 'portname': 'msp ', 'desc': '消息发送协议 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '19 ', 'portname': 'chargen ', 'desc': '字符生成服务；发送无止境的字符流 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '20 ', 'portname': 'ftp-data ', 'desc': 'FTP 数据端口 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '21 ', 'portname': 'ftp ', 'desc': '文件传输协议（FTP）端口；有时被文件服务协议（FSP）使用 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '22 ', 'portname': 'ssh ', 'desc': '安全 Shell（SSH）服务 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '23 ', 'portname': 'telnet ', 'desc': 'Telnet 服务 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '25 ', 'portname': 'smtp ', 'desc': '简单邮件传输协议（SMTP） ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '37 ', 'portname': 'time ', 'desc': '时间协议 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '39 ', 'portname': 'rlp ', 'desc': '资源定位协议 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '42 ', 'portname': 'nameserver ', 'desc': '互联网名称服务 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '43 ', 'portname': 'nicname ', 'desc': 'WHOIS 目录服务 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '49 ', 'portname': 'tacacs ', 'desc': '用于基于 TCP/IP 验证和访问的终端访问控制器访问控制系统 ',
              'type': 'UNIX 特有的端口', 'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '50 ', 'portname': 're-mail-ck ', 'desc': '远程邮件检查协议 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '53 ', 'portname': 'domain ', 'desc': '域名服务（如 BIND） ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '63 ', 'portname': 'whois++ ', 'desc': 'WHOIS++，被扩展了的 WHOIS 服务 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '67 ', 'portname': 'bootps ', 'desc': '引导协议（BOOTP）服务；还被动态主机配置协议（DHCP）服务使用 ',
              'type': 'UNIX 特有的端口', 'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '68 ', 'portname': 'bootpc ', 'desc': 'Bootstrap（BOOTP）客户；还被动态主机配置协议（DHCP）客户使用 ',
              'type': 'UNIX 特有的端口', 'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '69 ', 'portname': 'tftp ', 'desc': '小文件传输协议（TFTP） ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '70 ', 'portname': 'gopher ', 'desc': 'Gopher 互联网文档搜寻和检索 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '71 ', 'portname': 'netrjs-1 ', 'desc': '远程作业服务 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '72 ', 'portname': 'netrjs-2 ', 'desc': '远程作业服务 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '73 ', 'portname': 'netrjs-3 ', 'desc': '远程作业服务 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '73 ', 'portname': 'netrjs-4 ', 'desc': '远程作业服务 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '79 ', 'portname': 'finger ', 'desc': '用于用户联系信息的 Finger 服务 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '80 ', 'portname': 'http ', 'desc': '用于万维网（WWW）服务的超文本传输协议（HTTP） ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '88 ', 'portname': 'kerberos ', 'desc': 'Kerberos 网络验证系统 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '95 ', 'portname': 'supdup ', 'desc': 'Telnet 协议扩展 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '101 ', 'portname': 'hostname ', 'desc': 'SRI-NIC 机器上的主机名服务 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '102 ', 'portname': 'iso-tsap ', 'desc': 'ISO 开发环境（ISODE）网络应用 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '105 ', 'portname': 'csnet-ns ', 'desc': '邮箱名称服务器；也被 CSO 名称服务器使用 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '107 ', 'portname': 'rtelnet ', 'desc': '远程 Telnet ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '109 ', 'portname': 'pop2 ', 'desc': '邮局协议版本2 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '110 ', 'portname': 'pop3 ', 'desc': '邮局协议版本3 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '111 ', 'portname': 'sunrpc ', 'desc': '用于远程命令执行的远程过程调用（RPC）协议，被网络文件系统（NFS）使用 ',
              'type': 'UNIX 特有的端口', 'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '113 ', 'portname': 'auth ', 'desc': '验证和身份识别协议 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '115 ', 'portname': 'sftp ', 'desc': '安全文件传输协议（SFTP）服务 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '117 ', 'portname': 'uucp-path ', 'desc': 'Unix 到 Unix 复制协议（UUCP）路径服务 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '119 ', 'portname': 'nntp ', 'desc': '用于 USENET 讨论系统的网络新闻传输协议（NNTP） ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '123 ', 'portname': 'ntp ', 'desc': '网络时间协议（NTP） ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '137 ', 'portname': 'netbios-ns ', 'desc': '在红帽企业 Linux 中被 Samba 使用的 NETBIOS 名称服务 ',
              'type': 'UNIX 特有的端口', 'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '138 ', 'portname': 'netbios-dgm ', 'desc': '在红帽企业 Linux 中被 Samba 使用的 NETBIOS 数据报服务 ',
              'type': 'UNIX 特有的端口', 'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '139 ', 'portname': 'netbios-ssn ', 'desc': '在红帽企业 Linux 中被 Samba 使用的NET BIOS 会话服务 ',
              'type': 'UNIX 特有的端口', 'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '143 ', 'portname': 'imap ', 'desc': '互联网消息存取协议（IMAP） ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '161 ', 'portname': 'snmp ', 'desc': '简单网络管理协议（SNMP） ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '162 ', 'portname': 'snmptrap ', 'desc': 'SNMP 的陷阱 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '163 ', 'portname': 'cmip-man ', 'desc': '通用管理信息协议（CMIP） ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '164 ', 'portname': 'cmip-agent ', 'desc': '通用管理信息协议（CMIP） ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '174 ', 'portname': 'mailq ', 'desc': 'MAILQ ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '177 ', 'portname': 'xdmcp ', 'desc': 'X 显示管理器控制协议 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '178 ', 'portname': 'nextstep ', 'desc': 'NeXTStep 窗口服务器 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '179 ', 'portname': 'bgp ', 'desc': '边界网络协议 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '191 ', 'portname': 'prospero ', 'desc': 'Cliffod Neuman 的 Prospero 服务 ',
              'type': 'UNIX 特有的端口', 'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '194 ', 'portname': 'irc ', 'desc': '互联网中继聊天（IRC） ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '199 ', 'portname': 'smux ', 'desc': 'SNMP UNIX 多路复用 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '201 ', 'portname': 'at-rtmp ', 'desc': 'AppleTalk 选路 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '202 ', 'portname': 'at-nbp ', 'desc': 'AppleTalk 名称绑定 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '204 ', 'portname': 'at-echo ', 'desc': 'AppleTalk echo 服务 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '206 ', 'portname': 'at-zis ', 'desc': 'AppleTalk 区块信息 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '209 ', 'portname': 'qmtp ', 'desc': '快速邮件传输协议（QMTP） ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '210 ', 'portname': 'z39.50 ', 'desc': 'NISO Z39.50 数据库 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '213 ', 'portname': 'ipx ', 'desc': '互联网络分组交换协议（IPX），被 Novell Netware 环境常用的数据报协议 ',
              'type': 'UNIX 特有的端口', 'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '220 ', 'portname': 'imap3 ', 'desc': '互联网消息存取协议版本3 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '245 ', 'portname': 'link ', 'desc': 'LINK ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '347 ', 'portname': 'fatserv ', 'desc': 'Fatmen 服务器 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '363 ', 'portname': 'rsvp_tunnel ', 'desc': 'RSVP 隧道 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '369 ', 'portname': 'rpc2portmap ', 'desc': 'Coda 文件系统端口映射器 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '370 ', 'portname': 'codaauth2 ', 'desc': 'Coda 文件系统验证服务 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '372 ', 'portname': 'ulistproc ', 'desc': 'UNIX Listserv ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '389 ', 'portname': 'ldap ', 'desc': '轻型目录存取协议（LDAP） ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '427 ', 'portname': 'svrloc ', 'desc': '服务位置协议（SLP） ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '434 ', 'portname': 'mobileip-agent ', 'desc': '可移互联网协议（IP）代理 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '435 ', 'portname': 'mobilip-mn ', 'desc': '可移互联网协议（IP）管理器 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '443 ', 'portname': 'https ', 'desc': '安全超文本传输协议（HTTP） ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '444 ', 'portname': 'snpp ', 'desc': '小型网络分页协议 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '445 ', 'portname': 'microsoft-ds ', 'desc': '通过 TCP/IP 的服务器消息块（SMB） ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '464 ', 'portname': 'kpasswd ', 'desc': 'Kerberos 口令和钥匙改换服务 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '468 ', 'portname': 'photuris ', 'desc': 'Photuris 会话钥匙管理协议 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '487 ', 'portname': 'saft ', 'desc': '简单不对称文件传输（SAFT）协议 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '488 ', 'portname': 'gss-http ', 'desc': '用于 HTTP 的通用安全服务（GSS） ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '496 ', 'portname': 'pim-rp-disc ', 'desc': '用于协议独立的多址传播（PIM）服务的会合点发现（RP-DISC） ',
              'type': 'UNIX 特有的端口', 'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '500 ', 'portname': 'isakmp ', 'desc': '互联网安全关联和钥匙管理协议（ISAKMP） ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '535 ', 'portname': 'iiop ', 'desc': '互联网内部对象请求代理协议（IIOP） ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '538 ', 'portname': 'gdomap ', 'desc': 'GNUstep 分布式对象映射器（GDOMAP） ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '546 ', 'portname': 'dhcpv6-client ', 'desc': '动态主机配置协议（DHCP）版本6客户 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '547 ', 'portname': 'dhcpv6-server ', 'desc': '动态主机配置协议（DHCP）版本6服务 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '554 ', 'portname': 'rtsp ', 'desc': '实时流播协议（RTSP） ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '563 ', 'portname': 'nntps ', 'desc': '通过安全套接字层的网络新闻传输协议（NNTPS） ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '565 ', 'portname': 'whoami ', 'desc': 'whoami ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '587 ', 'portname': 'submission ', 'desc': '邮件消息提交代理（MSA） ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '610 ', 'portname': 'npmp-local ', 'desc': '网络外设管理协议（NPMP）本地 / 分布式排队系统（DQS） ',
              'type': 'UNIX 特有的端口', 'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '611 ', 'portname': 'npmp-gui ', 'desc': '网络外设管理协议（NPMP）GUI / 分布式排队系统（DQS） ',
              'type': 'UNIX 特有的端口', 'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '612 ', 'portname': 'hmmp-ind ', 'desc': 'HMMP 指示 / DQS ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '631 ', 'portname': 'ipp ', 'desc': '互联网打印协议（IPP） ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '636 ', 'portname': 'ldaps ', 'desc': '通过安全套接字层的轻型目录访问协议（LDAPS） ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '674 ', 'portname': 'acap ', 'desc': '应用程序配置存取协议（ACAP） ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '694 ', 'portname': 'ha-cluster ', 'desc': '用于带有高可用性的群集的心跳服务 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '749 ', 'portname': 'kerberos-adm ', 'desc': 'Kerberos 版本5（v5）的“kadmin”数据库管理 ',
              'type': 'UNIX 特有的端口', 'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '750 ', 'portname': 'kerberos-iv ', 'desc': 'Kerberos 版本4（v4）服务 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '765 ', 'portname': 'webster ', 'desc': '网络词典 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '767 ', 'portname': 'phonebook ', 'desc': '网络电话簿 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '873 ', 'portname': 'rsync ', 'desc': 'rsync 文件传输服务 ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '992 ', 'portname': 'telnets ', 'desc': '通过安全套接字层的 Telnet（TelnetS） ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '993 ', 'portname': 'imaps ', 'desc': '通过安全套接字层的互联网消息存取协议（IMAPS） ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '994 ', 'portname': 'ircs ', 'desc': '通过安全套接字层的互联网中继聊天（IRCS） ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '995 ', 'portname': 'pop3s ', 'desc': '通过安全套接字层的邮局协议版本3（POPS3） ', 'type': 'UNIX 特有的端口',
              'type_desc': '以下端口是 UNIX 特有的，涉及了从电子邮件到验证不等的服务'},
             {'port': '1080 ', 'portname': 'socks ', 'desc': 'SOCKS 网络应用程序代理服务 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '1236 ', 'portname': 'bvcontrol [rmtcfg] ', 'desc': 'Garcilis Packeten 远程配置服务器',
              'type': '注册的端口', 'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '1300 ', 'portname': 'h323hostcallsc ', 'desc': 'H.323 电话会议主机电话安全 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '1433 ', 'portname': 'ms-sql-s ', 'desc': 'Microsoft SQL 服务器 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '1434 ', 'portname': 'ms-sql-m ', 'desc': 'Microsoft SQL 监视器 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '1494 ', 'portname': 'ica ', 'desc': 'Citrix ICA 客户 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '1512 ', 'portname': 'wins ', 'desc': 'Microsoft Windows 互联网名称服务器 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '1524 ', 'portname': 'ingreslock ', 'desc': 'Ingres 数据库管理系统（DBMS）锁定服务 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '1525 ', 'portname': 'prospero-np ', 'desc': '无特权的 Prospero ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '1645 ', 'portname': 'datametrics [old-radius] ', 'desc': 'Datametrics / 从前的 radius 项目 ',
              'type': '注册的端口', 'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '1646 ', 'portname': 'sa-msg-port [oldradacct] ', 'desc': 'sa-msg-port / 从前的 radacct 项目 ',
              'type': '注册的端口', 'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '1649 ', 'portname': 'kermit ', 'desc': 'Kermit 文件传输和管理服务 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '1701 ', 'portname': 'l2tp [l2f] ', 'desc': '第2层隧道服务（LT2P） / 第2层转发（L2F） ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '1718 ', 'portname': 'h323gatedisc ', 'desc': 'H.323 电讯守门装置发现机制 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '1719 ', 'portname': 'h323gatestat ', 'desc': 'H.323 电讯守门装置状态 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '1720 ', 'portname': 'h323hostcall ', 'desc': 'H.323 电讯主持电话设置 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '1758 ', 'portname': 'tftp-mcast ', 'desc': '小文件 FTP 组播 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '1759 ', 'portname': 'mtftp ', 'desc': '组播小文件 FTP（MTFTP） ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '1789 ', 'portname': 'hello ', 'desc': 'Hello 路由器通信端口 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '1812 ', 'portname': 'radius ', 'desc': 'Radius 拨号验证和记帐服务 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '1813 ', 'portname': 'radius-acct ', 'desc': 'Radius 记帐 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '1911 ', 'portname': 'mtp ', 'desc': 'Starlight 网络多媒体传输协议（MTP） ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '1985 ', 'portname': 'hsrp ', 'desc': 'Cisco 热备用路由器协议 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '1986 ', 'portname': 'licensedaemon ', 'desc': 'Cisco 许可管理守护进程 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '1997 ', 'portname': 'gdp-port ', 'desc': 'Cisco 网关发现协议（GDP） ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '2049 ', 'portname': 'nfs [nfsd] ', 'desc': '网络文件系统（NFS） ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '2102 ', 'portname': 'zephyr-srv ', 'desc': 'Zephyr 通知传输和发送服务器 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '2103 ', 'portname': 'zephyr-clt ', 'desc': 'Zephyr serv-hm 连接 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '2104 ', 'portname': 'zephyr-hm ', 'desc': 'Zephyr 主机管理器 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '2401 ', 'portname': 'cvspserver ', 'desc': '并行版本系统（CVS）客户 / 服务器操作 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '2430/tcp ', 'portname': 'venus ', 'desc': '用于 Coda 文件系统（codacon 端口）的 Venus 缓存管理器 ',
              'type': '注册的端口', 'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '2430/udp ', 'portname': 'venus ',
              'desc': '用于 Coda 文件系统（callback/wbc interface 界面）的 Venus 缓存管理器 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '2431/tcp ', 'portname': 'venus-se ', 'desc': 'Venus 传输控制协议（TCP）的副作用 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '2431/udp ', 'portname': 'venus-se ', 'desc': 'Venus 用户数据报协议（UDP）的副作用 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '2432/udp ', 'portname': 'codasrv ', 'desc': 'Coda 文件系统服务器端口 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '2433/tcp ', 'portname': 'codasrv-se ', 'desc': 'Coda 文件系统 TCP 副作用 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '2433/udp ', 'portname': 'codasrv-se ', 'desc': 'Coda 文件系统 UDP SFTP 副作用 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '2600 ', 'portname': 'hpstgmgr [zebrasrv] ', 'desc': 'HPSTGMGR；Zebra 选路', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '2601 ', 'portname': 'discp-client [zebra] ', 'desc': 'discp 客户；Zebra 集成的 shell ',
              'type': '注册的端口', 'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '2602 ', 'portname': 'discp-server [ripd] ', 'desc': 'discp 服务器；选路信息协议守护进程（ripd） ',
              'type': '注册的端口', 'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '2603 ', 'portname': 'servicemeter [ripngd] ', 'desc': '服务计量；用于 IPv6 的 RIP 守护进程 ',
              'type': '注册的端口', 'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '2604 ', 'portname': 'nsc-ccs [ospfd] ', 'desc': 'NSC CCS；开放式短路径优先守护进程（ospfd） ',
              'type': '注册的端口', 'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '2605 ', 'portname': 'nsc-posa ', 'desc': 'NSC POSA；边界网络协议守护进程（bgpd） ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '2606 ', 'portname': 'netmon [ospf6d] ', 'desc': 'Dell Netmon；用于 IPv6 的 OSPF 守护进程（ospf6d） ',
              'type': '注册的端口', 'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '2809 ', 'portname': 'corbaloc ', 'desc': '公共对象请求代理体系（CORBA）命名服务定位器 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '3130 ', 'portname': 'icpv2 ', 'desc': '互联网缓存协议版本2（v2）；被 Squid 代理缓存服务器使用 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '3306 ', 'portname': 'mysql ', 'desc': 'MySQL 数据库服务 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '3346 ', 'portname': 'trnsprntproxy ', 'desc': 'Trnsprnt 代理 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '4011 ', 'portname': 'pxe ', 'desc': '执行前环境（PXE）服务 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '4321 ', 'portname': 'rwhois ', 'desc': '远程 Whois（rwhois）服务 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '4444 ', 'portname': 'krb524 ', 'desc': 'Kerberos 版本5（v5）到版本4（v4）门票转换器 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '5002 ', 'portname': 'rfe ', 'desc': '无射频以太网（RFE）音频广播系统 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '5308 ', 'portname': 'cfengine ', 'desc': '配置引擎（Cfengine） ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '5999 ', 'portname': 'cvsup [CVSup] ', 'desc': 'CVSup 文件传输和更新工具 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '6000 ', 'portname': 'x11 [X] ', 'desc': 'X 窗口系统服务 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '7000 ', 'portname': 'afs3-fileserver ', 'desc': 'Andrew 文件系统（AFS）文件服务器 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '7001 ', 'portname': 'afs3-callback ', 'desc': '用于给缓存管理器回电的 AFS 端口 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '7002 ', 'portname': 'afs3-prserver ', 'desc': 'AFS 用户和组群数据库 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '7003 ', 'portname': 'afs3-vlserver ', 'desc': 'AFS 文件卷位置数据库 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '7004 ', 'portname': 'afs3-kaserver ', 'desc': 'AFS Kerberos 验证服务 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '7005 ', 'portname': 'afs3-volser ', 'desc': 'AFS 文件卷管理服务器 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '7006 ', 'portname': 'afs3-errors ', 'desc': 'AFS 错误解释服务 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '7007 ', 'portname': 'afs3-bos ', 'desc': 'AFS 基本监查进程 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '7008 ', 'portname': 'afs3-update ', 'desc': 'AFS 服务器到服务器更新器 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '7009 ', 'portname': 'afs3-rmtsys ', 'desc': 'AFS 远程缓存管理器服务 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '9876 ', 'portname': 'sd ', 'desc': '会话指引器 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '10080 ', 'portname': 'amanda ', 'desc': '高级 Maryland 自动网络磁盘归档器（Amanda）备份服务 ',
              'type': '注册的端口', 'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '11371 ', 'portname': 'pgpkeyserver ', 'desc': '良好隐私（PGP） / GNU 隐私卫士（GPG）公钥服务器 ',
              'type': '注册的端口', 'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '11720 ', 'portname': 'h323callsigalt ', 'desc': 'H.323 调用信号交替 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '13720 ', 'portname': 'bprd ', 'desc': 'Veritas NetBackup 请求守护进程（bprd） ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '13721 ', 'portname': 'bpdbm ', 'desc': 'Veritas NetBackup 数据库管理器（bpdbm） ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'}, {'port': '13722 ', 'portname': 'bpjava-msvc ',
                                                                       'desc': 'Veritas NetBackup Java / Microsoft Visual C++ (MSVC) 协议 ',
                                                                       'type': '注册的端口',
                                                                       'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '13724 ', 'portname': 'vnetd ', 'desc': 'Veritas 网络工具 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '13782 ', 'portname': 'bpcd ', 'desc': 'Vertias NetBackup ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '13783 ', 'portname': 'vopied ', 'desc': 'Veritas VOPIED 协议 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '22273 ', 'portname': 'wnn6 [wnn4] ', 'desc': '假名/汉字转换系统', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '26000 ', 'portname': 'quake ', 'desc': 'Quake（以及相关的）多人游戏服务器 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '26208 ', 'portname': 'wnn6-ds ', 'desc': '&nbsp;', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '33434 ', 'portname': 'traceroute ', 'desc': 'Traceroute 网络跟踪工具 ', 'type': '注册的端口',
              'type_desc': '列举了由网络和软件社区向 IANA 提交的要在端口号码列表中正式注册的端口。'},
             {'port': '1/ddp ', 'portname': 'rtmp ', 'desc': '路由表管理协议 ', 'type': '数据报传递协议端口',
              'type_desc': '显示了一个和数据报传递协议（DDP）有关的端口列表。DDP 在 AppleTalk 网络上被使用。'},
             {'port': '2/ddp ', 'portname': 'nbp ', 'desc': '名称绑定协议 ', 'type': '数据报传递协议端口',
              'type_desc': '显示了一个和数据报传递协议（DDP）有关的端口列表。DDP 在 AppleTalk 网络上被使用。'},
             {'port': '4/ddp ', 'portname': 'echo ', 'desc': 'AppleTalk Echo 协议 ', 'type': '数据报传递协议端口',
              'type_desc': '显示了一个和数据报传递协议（DDP）有关的端口列表。DDP 在 AppleTalk 网络上被使用。'},
             {'port': '6/ddp ', 'portname': 'zip ', 'desc': '区块信息协议 ', 'type': '数据报传递协议端口',
              'type_desc': '显示了一个和数据报传递协议（DDP）有关的端口列表。DDP 在 AppleTalk 网络上被使用。'},
             {'port': '751 ', 'portname': 'kerberos_master ', 'desc': 'Kerberos 验证 ',
              'type': 'Kerberos（工程 Athena/MIT）端口',
              'type_desc': '和 Kerberos 网络验证协议相关的端口列表。在标记的地方，v5 代表 Kerberos 版本5协议。注意，这些端口没有在 IANA 注册。'},
             {'port': '752 ', 'portname': 'passwd_server ', 'desc': 'Kerberos 口令（kpasswd）服务器 ',
              'type': 'Kerberos（工程 Athena/MIT）端口',
              'type_desc': '和 Kerberos 网络验证协议相关的端口列表。在标记的地方，v5 代表 Kerberos 版本5协议。注意，这些端口没有在 IANA 注册。'},
             {'port': '754 ', 'portname': 'krb5_prop ', 'desc': 'Kerberos v5 从属传播 ',
              'type': 'Kerberos（工程 Athena/MIT）端口',
              'type_desc': '和 Kerberos 网络验证协议相关的端口列表。在标记的地方，v5 代表 Kerberos 版本5协议。注意，这些端口没有在 IANA 注册。'},
             {'port': '760 ', 'portname': 'krbupdate [kreg] ', 'desc': 'Kerberos 注册 ',
              'type': 'Kerberos（工程 Athena/MIT）端口',
              'type_desc': '和 Kerberos 网络验证协议相关的端口列表。在标记的地方，v5 代表 Kerberos 版本5协议。注意，这些端口没有在 IANA 注册。'},
             {'port': '1109 ', 'portname': 'kpop ', 'desc': 'Kerberos 邮局协议（KPOP） ',
              'type': 'Kerberos（工程 Athena/MIT）端口',
              'type_desc': '和 Kerberos 网络验证协议相关的端口列表。在标记的地方，v5 代表 Kerberos 版本5协议。注意，这些端口没有在 IANA 注册。'},
             {'port': '2053 ', 'portname': 'knetd ', 'desc': 'Kerberos 多路分用器 ', 'type': 'Kerberos（工程 Athena/MIT）端口',
              'type_desc': '和 Kerberos 网络验证协议相关的端口列表。在标记的地方，v5 代表 Kerberos 版本5协议。注意，这些端口没有在 IANA 注册。'},
             {'port': '2105 ', 'portname': 'eklogin ', 'desc': 'Kerberos v5 加密的远程登录（rlogin） ',
              'type': 'Kerberos（工程 Athena/MIT）端口',
              'type_desc': '和 Kerberos 网络验证协议相关的端口列表。在标记的地方，v5 代表 Kerberos 版本5协议。注意，这些端口没有在 IANA 注册。'},
             {'port': '15/tcp ', 'portname': 'netstat ', 'desc': '网络状态（netstat） ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '98/tcp ', 'portname': 'linuxconf ', 'desc': 'Linuxconf Linux 管理工具 ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '106 ', 'portname': 'poppassd ', 'desc': '邮局协议口令改变守护进程（POPPASSD） ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '465/tcp ', 'portname': 'smtps ', 'desc': '通过安全套接字层的简单邮件传输协议（SMTPS） ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '616/tcp ', 'portname': 'gii ', 'desc': '使用网关的（选路守护进程）互动界面 ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '808 ', 'portname': 'omirr [omirrd] ', 'desc': '联机镜像（Omirr）文件镜像服务 ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '871/tcp ', 'portname': 'supfileserv ', 'desc': '软件升级协议（SUP）服务器 ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '901/tcp ', 'portname': 'swat ', 'desc': 'Samba 万维网管理工具（SWAT） ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '953 ', 'portname': 'rndc ', 'desc': 'Berkeley 互联网名称域版本9（BIND 9）远程名称守护进程配置工具 ',
              'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '1127 ', 'portname': 'sufiledbg ', 'desc': '软件升级协议（SUP）调试 ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '1178/tcp ', 'portname': 'skkserv ', 'desc': '简单假名到汉字（SKK）日文输入服务器 ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '1313/tcp ', 'portname': 'xtel ', 'desc': '法国 Minitel 文本信息系统 ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '1529/tcp ', 'portname': 'support [prmsd, gnatsd] ', 'desc': 'GNATS 错误跟踪系统 ',
              'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '2003/tcp ', 'portname': 'cfinger ', 'desc': 'GNU Finger 服务 ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '2150 ', 'portname': 'ninstall ', 'desc': '网络安装服务 ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '2988 ', 'portname': 'afbackup ', 'desc': 'afbackup 客户-服务器备份系统 ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '3128/tcp ', 'portname': 'squid ', 'desc': 'Squid 万维网代理缓存 ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '3455 ', 'portname': 'prsvp ', 'desc': 'RSVP 端口 ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '5432 ', 'portname': 'postgres ', 'desc': 'PostgreSQL 数据库 ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '4557/tcp ', 'portname': 'fax ', 'desc': 'FAX 传输服务（旧服务） ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '4559/tcp ', 'portname': 'hylafax ', 'desc': 'HylaFAX 客户-服务器协议（新服务） ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '5232 ', 'portname': 'sgi-dgl ', 'desc': 'SGI 分布式图形库 ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '5354 ', 'portname': 'noclog ', 'desc': 'NOCOL 网络操作中心记录守护进程（noclogd） ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '5355 ', 'portname': 'hostmon ', 'desc': 'NOCOL 网络操作中心主机监视 ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '5680/tcp ', 'portname': 'canna ', 'desc': 'Canna 日文字符输入界面 ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '6010/tcp ', 'portname': 'x11-ssh-offset ', 'desc': '安全 Shell（SSH）X11 转发偏移 ',
              'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '6667 ', 'portname': 'ircd ', 'desc': '互联网中继聊天守护进程（ircd） ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '7100/tcp ', 'portname': 'xfs ', 'desc': 'X 字体服务器（XFS） ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '7666/tcp ', 'portname': 'tircproxy ', 'desc': 'Tircproxy IRC 代理服务 ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '8008 ', 'portname': 'http-alt ', 'desc': '超文本传输协议（HTTP）的另一选择 ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '8080 ', 'portname': 'webcache ', 'desc': '万维网（WWW）缓存服务 ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '8081 ', 'portname': 'tproxy ', 'desc': '透明代理 ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '9100/tcp ', 'portname': 'jetdirect [laserjet, hplj] ',
              'desc': 'Hewlett-Packard (HP) JetDirect 网络打印服务 ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '9359 ', 'portname': 'mandelspawn [mandelbrot] ', 'desc': '用于 X 窗口系统的并行 Mandelbrot 生成程序 ',
              'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '10081 ', 'portname': 'kamanda ', 'desc': '使用 Kerberos 的 Amanda 备份服务 ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '10082/tcp ', 'portname': 'amandaidx ', 'desc': 'Amanda 备份服务 ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '10083/tcp ', 'portname': 'amidxtape ', 'desc': 'Amanda 备份服务 ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '20011 ', 'portname': 'isdnlog ', 'desc': '综合业务数字网（ISDN）登录系统 ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '20012 ', 'portname': 'vboxd ', 'desc': 'ISDN 音箱守护进程（vboxd） ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '22305/tcp ', 'portname': 'wnn4_Kr ', 'desc': 'kWnn 韩文输入系统 ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '22289/tcp ', 'portname': 'wnn4_Cn ', 'desc': 'cWnn 中文输入系统 ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '22321/tcp ', 'portname': 'wnn4_Tw ', 'desc': 'tWnn 中文输入系统（台湾） ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '24554 ', 'portname': 'binkp ', 'desc': 'Binkley TCP/IP Fidonet 邮寄程序守护进程 ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '27374 ', 'portname': 'asp ', 'desc': '地址搜索协议 ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '60177 ', 'portname': 'tfido ', 'desc': 'Ifmail FidoNet 兼容邮寄服务 ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'},
             {'port': '60179 ', 'portname': 'fido ', 'desc': 'FidoNet 电子邮件和新闻网络 ', 'type': '未注册的端口',
              'type_desc': '一个未注册的端口列表。这些端口可能被安装在你的红帽企业 Linux 系统上的服务或协议使用，或者它们是在红帽企业 Linux 和运行其它操作系统的机器通信所必需的端口。'}]}
