# Generated by Django 2.0.12 on 2019-07-11 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_name', models.CharField(max_length=200, verbose_name='组织名称')),
                ('responsibility', models.TextField(default='-', verbose_name='责任书')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_conn_group', to='auth.Group', verbose_name='用户组')),
            ],
            options={
                'verbose_name': '审计用户操作',
                'db_table': 'community',
                'ordering': ['-date_updated'],
            },
        ),
        migrations.CreateModel(
            name='PlatOptHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(default='', max_length=155, verbose_name='操作描述')),
                ('type', models.CharField(default='平台日志', max_length=155, verbose_name='操作类型')),
                ('extra', models.CharField(default='', max_length=155, verbose_name='备用字段')),
                ('opreatername', models.CharField(default='actanble', max_length=55, verbose_name='操作者')),
                ('opreate_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
                ('conn_file', models.CharField(default='', max_length=255, verbose_name='关联文件')),
                ('remote_file', models.CharField(default='', max_length=255, verbose_name='远程文件')),
            ],
            options={
                'verbose_name': '操作历史记录',
                'ordering': ['-opreate_time'],
            },
        ),
        migrations.CreateModel(
            name='UserAuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='/waf/mg/jwt_login/', max_length=255, verbose_name='请求URL')),
                ('request_method', models.CharField(default='POST', max_length=255, verbose_name='请求方法')),
                ('args', models.TextField(default='-', verbose_name='操作参数')),
                ('ip', models.GenericIPAddressField(default='0.0.0.0', verbose_name='IP')),
                ('username', models.CharField(max_length=255, verbose_name='访问的用户的用户名')),
                ('status', models.CharField(choices=[('200', '正常'), ('400', '请求错误'), ('403', '访问阻断'), ('401', '认证失败')], default='200', max_length=5, verbose_name='请求状态')),
                ('opreate_time', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
                ('param', models.CharField(default='', max_length=255, verbose_name='参数')),
            ],
            options={
                'verbose_name': '审计用户操作',
                'db_table': 'user_auditlog',
                'ordering': ['-opreate_time'],
            },
        ),
    ]
