# Generated by Django 2.0.12 on 2019-07-15 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ['-date_updated'], 'verbose_name': '组织'},
        ),
    ]
