FROM actanble/kali2

RUN apt-get -f install gobuster wpscan nikto whatweb\
searchsploit   sqlmap photon cewl ncrack \
sslscan crowbar sslyze dnsrecon hydra ncrack onesixtyone medusa \
nmblookup  smbclient  enum4linux  rpcclient  ncat

amass sublist3r